### ISSUE TITLE
How do u use it?

### ISSUE THREAD

**Issue by Xboy3998** [SergeyMC9730/deathreplay#1]
I died in a level and nothing happens. Is there a button somewhere? Also, you say that buttons are in the mod settings but i only see show particles and stuff. I can't enable ghost replay or something. Can you explain to me precisely how to enable stuff?

**Comment by SergeyMC9730** [comment]
uuh you need geode

**Comment by SergeyMC9730** [comment]
Mod settings are inside geode's mod menu
![image](https://github.com/SergeyMC9730/deathreplay/assets/57207009/6b46bf29-8d51-4df5-8b60-2a23f0a4a9e1)
Show Ghost setting is turned off by default

after turning this option up Ghost would be shown up on your screen
![image](https://github.com/SergeyMC9730/deathreplay/assets/57207009/55507966-a370-4d6a-ba1a-fd911d5208eb)

If you don't see this option, then installed mod is outdated and you need to install a new version of it. Current version is v1.1.0 (In Geode indexer shows as v1.0.2 cuz i forgot to change mod metadata)
![image](https://github.com/SergeyMC9730/deathreplay/assets/57207009/b86aaf70-b0ef-4d31-9e4a-25b63c556e4f)
