### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by LousyBook-01** [SergeyMC9730/deathreplay#10]
the game crashes when you are in the editor and you die to something, also don't know if other mods affect this mod, when i disable this mod, it works fine

**Comment by SergeyMC9730** [comment]
can you provide crashlog please?

**Comment by LousyBook-01** [comment]
[2024-07-04_17-32-11.txt](https://github.com/user-attachments/files/16114848/2024-07-04_17-32-11.txt)
sorry i have a hella lot of mods

**Comment by SergeyMC9730** [comment]
bug has been caught and would be fixed soon!

**Comment by LousyBook-01** [comment]
@SergeyMC9730 tysm :D

**Comment by SergeyMC9730** [comment]
fixed in `v1.2.4`
