### ISSUE TITLE
Add opacity slider in settings

### ISSUE THREAD

**Issue by iiDk-the-actual** [SergeyMC9730/deathreplay#11]
This mod is great, I have it on all the time, but something I find annoying is that sometimes the Xs mess me up when I'm in gameplay. Is there any way to lower the opacity of them?

**Comment by SergeyMC9730** [comment]
I had some plans to implement this in the future but still thank you for asking for a feature!
Your idea would be implemented in v1.2.5.

For now you can just disable X rendering

**Comment by SergeyMC9730** [comment]
Added in `1.2.5`
