### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by GWDdoS** [SergeyMC9730/deathreplay#3]
Yes lastest update
no, i did not turn it off.

**Comment by SergeyMC9730** [comment]
please explain whats happenning with installed death replay mod, i dont understand currently.

**Comment by GWDdoS** [comment]
I just installed via Geode, but it seems to load, but no X gets made or shown

**Comment by SergeyMC9730** [comment]
Check mod settings, maybe you've disabled something

**Comment by GWDdoS** [comment]
Nopei checked

**Comment by SergeyMC9730** [comment]
Hmmok. Do you have player death effects disabled in some mod menu like Megahack?

**Comment by GWDdoS** [comment]
Yes...

**Comment by SergeyMC9730** [comment]
Then enable them...

**Comment by GWDdoS** [comment]
does that fix it?

**Comment by SergeyMC9730** [comment]
yes i think
