### ISSUE TITLE
Game Crashes With Mod Enabled

### ISSUE THREAD

**Issue by MasterGamerY** [SergeyMC9730/deathreplay#4]
Issue: The game crashes whenever this mod is enabled. 
 How to Recreate: Make sure this mod is enabled and play a random level. When you exit the level the game crashes (see attached crashlog). This does not happen with the mod disabled.
[2024-01-30_17-59-57.log](https://github.com/SergeyMC9730/deathreplay/files/14105327/2024-01-30_17-59-57.log)

**Comment by SergeyMC9730** [comment]
Unfortunately I'm not able to replicate this issue even with installed mods list in this crash log. As far as I can tell from this crash is that Geode tried to make web request and notify user about that but failed while switching Scenes and due to this game got crashed.
