### ISSUE TITLE
Suggestion: Option to only show death markers when you die

### ISSUE THREAD

**Issue by 7ih** [SergeyMC9730/deathreplay#9]
The death markers are a bit distracting on harder levels so it would be nice if there was an option to only show the death markers immediately after you die (like in mario maker).

**Comment by SergeyMC9730** [comment]
Isn't it what "Death Markers" mod did before? Also spawning a bunch of death markers at the same time is a bad idea I think.

**Comment by 7ih** [comment]
Sorry I didn't know about that mod
